pipeline {
    agent any
    stages {
        stage('Deploy') {
            steps {
		sshagent(['ssh-key']){
                sh '''
                sudo ssh vleena1@invrhel801.informatica.com "
                cd cicd-flask-deployment &&
                git pull &&
                pkill -f app.py || true &&
                nohup python3 app.py > output.log 2>&1 &
		"
                '''
		}
            }
        }
    }
}
